services:
    db:
        build: services/db
        environment:
                - POSTGRES_USER=postgres
                - POSTGRES_PASSWORD=postgres
                - POSTGRES_DB=video_db
        ports:
            - "5432:5432"
        volumes:
            - ./pg_data:/var/lib/postgresql/data

    python:
        build: services/python
        ports:
            - "8000:8000"
        depends_on:
            - db
        volumes:
            - ./services/python:/code
